data_sources:
  movies_metadata_csv: "archive/movies_metadata.csv"
  ratings_csv: "archive/ratings_small.csv"
write_locations:
  processed_dataframes: "processed_dataframes"
log_locations:
  movies_transforms_logs: "logging/movies_transforms.log"
